
  name: v4l2camera
  version: git
  summary: Web interface to V4L2 
  description: |
    This is a Web interface to v4L2rtspserver, the http server use civetweb, the RTSP server live555. 

  grade: stable 
  confinement: strict
  base: core24
  license: Unlicense
  contact: michel.promonet@free.fr
  platforms:
    amd64:
    arm64:
    armhf:
    ppc64el:
    s390x:
  
  parts:  
    v4l2camera:
      plugin: cmake
      source: .
      build-packages:
        - g++
        - pkg-config
        - libssl-dev
        - libasound2-dev
        - npm
      stage-packages:
        - libssl-dev
        - libasound2        
      cmake-parameters:
        - -DWITH_COMPRESS=OFF

  apps:
    v4l2camera:
      command: usr/local/bin/v4l2camera -p $SNAP/usr/local/share/v4l2camera
      daemon: simple   
      plugs: [network-bind, camera, alsa]
