
  name: v4l2camera
  version: git
  summary: Web interface to V4L2 
  description: |
    This is a Web interface to v4L2rtspserver, the http server use civetweb, the RTSP server live555. 

  grade: stable 
  confinement: strict
  base: core24
  license: Unlicense
  contact: michel.promonet@free.fr

  parts:
    ui:
      plugin: npm
      npm-node-version: 20.16.0
      npm-include-node: true
      source: vuejs
  
    v4l2camera:
      plugin: cmake
      source: .
      build-packages:
        - g++
        - pkg-config
        - libssl-dev
        - libasound2-dev
      stage-packages:
        - libssl3
        - libasound2        
      build-environment:
        - PATH: $SNAPCRAFT_PART_INSTALL/../../ui/install/bin:$PATH       
      cmake-parameters:
        - -DWITH_COMPRESS=OFF

  apps:
    v4l2camera:
      command: usr/local/bin/v4l2camera -p $SNAP/usr/local/share/v4l2camera
      daemon: simple   
      plugs: [network-bind, camera, alsa]
