name: C/C++ CI linux cross compilation

on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
        - buildtype: Debug
          system: arm64
          crosscompiler: aarch64-linux-gnu
        - buildtype: Release
          system: arm64
          crosscompiler: aarch64-linux-gnu

        - buildtype: Debug
          system: armhf
          crosscompiler: arm-linux-gnueabihf
        - buildtype: Release
          system: armhf
          crosscompiler: arm-linux-gnueabihf

        - buildtype: Debug
          system: arm
          crosscompiler: arm-linux-gnueabi
        - buildtype: Release
          system: arm
          crosscompiler: arm-linux-gnueabi

        - buildtype: Debug
          system: mips
          crosscompiler: mips-linux-gnu
        - buildtype: Release
          system: mips
          crosscompiler: mips-linux-gnu

        - buildtype: Debug
          system: mipsel
          crosscompiler: mipsel-linux-gnu
        - buildtype: Release
          system: mipsel
          crosscompiler: mipsel-linux-gnu

        - buildtype: Debug
          system: riscv64
          crosscompiler: riscv64-linux-gnu
        - buildtype: Release
          system: riscv64
          crosscompiler: riscv64-linux-gnu

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - run: git fetch --prune --unshallow --tags

    - name: pkg
      run: | 
        sudo apt-get update 
        sudo apt-get install -y --no-install-recommends ca-certificates g++ autoconf automake libtool xz-utils cmake make pkg-config git
        sudo apt-get install -y --no-install-recommends  g++-${{ matrix.crosscompiler }}

    - name: build
      run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.system }} -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_C_COMPILER=${{ matrix.crosscompiler }}-gcc -DCMAKE_CXX_COMPILER=${{ matrix.crosscompiler }}-g++ -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY -DWITH_SSL=OFF .
          make

    - name: cpack 
      run: | 
          rm -f *.tar.gz
          cpack
          echo "artifactPath=$(ls *.tar.gz)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifactPath }}
        path: ${{ env.artifactPath }}   

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.artifactPath }}