name: Node.js Package

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
              git submodule update --init
              git fetch --prune --unshallow --tags
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  
      - run: |
              cd vuejs
              npm install
              npm config set git-tag-version=false
              npm version $(git describe --tags --always)
              npm run build
              npm publish --provenance --access public

